#

sessionApi:
  image:
    repository: docker.io/mminichino/redis-session-api-test
    tag: ""
    pullPolicy: Always

runner:
  image:
    repository: docker.io/mminichino/java-runner
    tag: ""
    pullPolicy: Always

redisHost: ""
redisPassword: ""
redisPort: "12000"
replicas: 1
servicePort: 8080
openshift: false
