#

sessionApi:
  image:
    repository: docker.io/mminichino/redis-session-api-test
    tag: ""
    pullPolicy: Always

runner:
  image:
    repository: docker.io/mminichino/java-runner
    tag: "2.0.1"
    pullPolicy: Always

redisHost: ""
redisPassword: ""
redisPort: "12000"
replicas: 4
servicePort: 8080

ingress:
  route: false
  lb: false
