{{- if .Values.ingress.lb }}
apiVersion: v1
kind: Service
metadata:
  name: session-api-lb
  namespace: {{ .Release.Namespace }}
  labels:
    app: session-api
spec:
  type: LoadBalancer
  selector:
    app: session-api
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.servicePort }}
      protocol: TCP
  sessionAffinity: None
{{- end }}
